### ISSUE TITLE
Optimise Kamienny's Formal Immersion result

### ISSUE THREAD

**Issue by BarinderBanwait** [isogeny-primes/isogeny-primes#2]
@koffie Your 'Improvement 3' was:

>I think that using the results of Pierre Parent it should be possible to also use 3 and 5 as auxiliary primes in proposition 3.1 by using the work of Pierre Parent, and that it should also be possible to maybe sometimes exclude type one primes <= 71 if we do some careful computation using formal immersions. I don't know whether this actually helps in the global argument because I don't know what kind of bounds one obtains in other situations. 

This would be a massive saving, to be able to cut down the primes we need to throw into TypeOnePrimes at the outset. A concrete goal of this issue is:

**Goal: Determine the best possible Kamienny Proposition 3.2**

**Comment by BarinderBanwait** [comment]
@koffie is the following true after Parent's Prop 1.7:

Let d be an integer, and p a prime > 65(2d)^6. Then the map f : X_0(p)^(d) --> J_0^e over Spec Z[1/p] is a formal immersion along the infinite section in all characteristics.

If so, then we can replace the 73 for quadratic fields with 65(2d)^6 for degree d fields, and the 7 for auxiliary primes with 2.

But this bound is quite big. In Kamienny's paper he does some explicit computations with Wada's tables and characteristic polynomials of T_2. What would the analogue of those explicit computations be in Parent's case? I think we should try to write an algorithm which computes whether Parent's Theorem 1.6 Part (2) holds; this will give us the best possible formal immersion result

**Comment by koffie** [comment]
@BarinderBanwait 

You are almost correct. You need to combine Prop 1.7 with Theorem 1.6 to get the formal immersion statement. 
And one important assumption is a bit hidden, but right before Prop 1.3 he says: `Soit l un nombre premier différent de 2 et de p` In particular Parents results in that article only give formal immersion in characteristics away from 2 and p. So what you say is true if you restrict to characteristics other then 2 and p instead of all characteristics (note that characteristic p is already excluded by working over Z[1/p] it is mostly that characteristic 2 is easy to miss if you don't know the entire article) .

If we want to use the prime 2 as well in addition then this requires some extra computations, in https://arxiv.org/pdf/alg-geom/9611022.pdf these extra computations are explained for cubic fields (using X_1(p) rather then X_0(p)). How to do this for higher degree numberfields and X_0(p) is explained in https://arxiv.org/abs/1707.00364 (and as I worked that out personally I know very well how this works ;)). In Lemma 5.4 of that article the outcomes of explicit computations for d < 8 and p < 2282 are given. So this gives some range of primes p for which we can use 2 as auxiliary prime. Note that in practice it is not so bad that we can only use 2 for small primes p, because for larger primes p the auxiliary primes > 2 will probably suffice.

As you say 65(2d)^6 is quite large, and for primes > 2 this can be lowered using explicit computations. These computations are due to Oesterle and explained in section 6 of https://arxiv.org/pdf/1707.00364.pdf . Corollary 6.8 there is actually not as general as it could be. The statement that could be derived there:

**Corollary 6.8 improved** Let l > 2 be a prime, d and M be as in Lemma 6.7 and fix u in Z coprime
with M. If the matrix from Corollary 6.8 with entries taken in F_l, has rank d, then the map f : X_0(p)^(d) --> J_0^e is a formal immersion along the infinite section in characteristic l for all primes 
p > 2dM different from l such that pu ≡ 1 mod M .

This could be used to significantly lower 65(2d)^6. However after that it could probably be lowered even further by doing computations similar to those used in Lemma 5.4 (the reason to not directly do computations in the style of Lemma 5.4 is that **Corollary 6.8 improved** is computationally much less expensive than those used in Lemma 5.4, especially when p is big (i.e. close to 65(2d)^6).

p.s. When writing stuff in overleaf or referencing stuff in source code rather in comments we should not use the numbering of https://arxiv.org/pdf/alg-geom/9611022.pdf cause I know the numbering there to be different from the published version.

**Comment by koffie** [comment]
Hi Barinder,

I found the code that constructs Oesterle's matrix. I modified the code a bit in order to get a list of pairs, d, M_d such that we can use corollary 6.8 for all auxilary primes > 2, and all residue classes of p mod M_d. 

In particular if p > 2dM_d in the list below, then we can use all auxiliary primes  q > 2 and q different from p to try and prove that p is not an isogeny prime over a number field of degree d.

d = 3, M_d = 29, lcm = []
d = 4, M_d = 37, lcm = []
d = 5, M_d = 41, lcm = [2]
d = 6, M_d = 43, lcm = [2]
d = 7, M_d = 47, lcm = [2]
d = 8, M_d = 47, lcm = [2]
d = 9, M_d = 53, lcm = [2]
d = 10, M_d = 53, lcm = [2]
d = 11, M_d = 61, lcm = []
d = 12, M_d = 61, lcm = [2]
d = 13, M_d = 73, lcm = [2]
d = 14, M_d = 73, lcm = [2]
d = 15, M_d = 79, lcm = [2]
d = 16, M_d = 79, lcm = [2]
d = 17, M_d = 89, lcm = [2]
d = 18, M_d = 89, lcm = [2]
d = 19, M_d = 89, lcm = [2]
d = 20, M_d = 101, lcm = [2]
d = 21, M_d = 101, lcm = [2]
d = 22, M_d = 109, lcm = [2]
d = 23, M_d = 109, lcm = [2]
d = 24, M_d = 109, lcm = [2]
d = 25, M_d = 127, lcm = [2]
d = 26, M_d = 127, lcm = [2]

In particular for d = 3 we can already use Momoses work for p > 174 . However I expect the 174 to be far from sharp. I expect with some extra work for d = 3 we should be able to handle  p > 46  and p not one of 73, 79 .

The code and the calculations can be found in a cocalc project that I shared with you. I have the feeling the code has a memory leak but I do not see where it comes from....

**Comment by koffie** [comment]
For degrees < 8 these are the p > 10 that d not work with any auxiliary prime q.

{1: [13],
 2: [11, 13, 17, 19, 37],
 3: [11, 13, 17, 19, 23, 29, 31, 37, 43, 73],
 4: [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 53, 61, 67, 73, 97],
 5: [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 61, 67, 73, 97],
 6: [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 73, 79, 83, 97, 103, 109, 113],
 7: [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 103, 107, 109, 113, 127, 137, 157]}

There are also some values of p for which some specific auxiliary primes q don't work: format is {d : {p:q}}

{1: {},
 2: {},
 3: {},
 4: {109: 3},
 5: {109: 3, 113: 3},
 6: {71: 3},
 7: {163: 5}}

If d < 8, and the triple d,p,q is not listed above then all auxiliary primes (except for possibly 2 and p) work.

**Comment by BarinderBanwait** [comment]
wow, this is fantastic stuff :star_struck: but let me just confirm one thing: when you write:

```
For degrees < 8 these are the p > 10 that d not work with any auxiliary prime q.

{1: [13],
2: [11, 13, 17, 19, 37],
3: [11, 13, 17, 19, 23, 29, 31, 37, 43, 73],
4: [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 53, 61, 67, 73, 97],
5: [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 61, 67, 73, 97],
6: [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 73, 79, 83, 97, 103, 109, 113],
7: [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 103, 107, 109, 113, 127, 137, 157]}
```

does this mean that these are the only possible Type One primes for number fields of that degree? If so, that is amazing; which auxiliary primes did you use to get these?

**Comment by koffie** [comment]
Hi @BarinderBanwait,

The list above does not say that the above are the only primes that can be a type one prime for those degrees! We also have to include the divisors of D(q) as you mention later in your tekst.

Yes, concretely it means that we can now do type one primes for degree < 8. We need to initialize TypeOnePrimes with that set (and the primes < 11 of course since I didn't bother to check those). After that we don't actually need to check primes p up to 2dM_d, since I already did that check, and the outcome of the failing checks is the list above. 

Also checking when we have a formal immersion for the primes not in the list is something that I already did. And for the primes not in the list you almost always have a formal immersion in characteristic > 2 (and unequal to p). The following list is just the set of combinations of d,p and q for which we do not have a formal immersion ( the cases q=2 and q=p): using the format: {d : {p:q}}

{1: {},
2: {},
3: {},
4: {109: 3},
5: {109: 3, 113: 3},
6: {71: 3},
7: {163: 5}}

as you can see it are just the auxiliary primes 3 and 5 that sometimes are not available for certain primes p. However this set of exceptions is really small. So outside this small list of exceptions, we either have a formal immersion in all characteristics except possibly 2,p, or it is nowhere a formal immersion.

**Comment by koffie** [comment]
> The code and the calculations can be found in a cocalc project that I shared with you. I have the feeling the code has a memory leak but I do not see where it comes from....

Just confirmed the memory leak:

https://trac.sagemath.org/ticket/31340

Knowing the source of the leak I was able to prevent the code from leaking memory by preventing the use of lists of integers.

**Comment by BarinderBanwait** [comment]
I believe that this is now done @koffie? Though I have one question ... on line 170 in `isogeny_primes.py`:

https://github.com/isogeny-primes/isogeny-primes/blob/d27f68915557fa80e78776f2fbaaf57c00fb7e34/isogeny_primes.py#L170

why do we stop at 402? Should that be `2*d*M_d`?



PS: good catch on that memory leak!

**Comment by koffie** [comment]
> 
> why do we stop at 402? Should that be `2*d*M_d`?
> 
Yes, this is I guess since you were a bit eager on putting the code from the ipython notebooks into this repo. As you can see the 2*d*M_d is in the ipython notebook but a bit lower then the code you put into the pull request. This also has to do with my comment in the review of pull request  #7 that it is a two stage process, let's keep this issue open till I provided a nice version of get_bad_formal_immersion_data.
![tmp](https://user-images.githubusercontent.com/773234/112455325-e6e05780-8d59-11eb-9bf2-a5f68ac0ea80.jpeg)

**Comment by BarinderBanwait** [comment]
ok thanks Maarten, sorry for rushing!

**Comment by koffie** [comment]
I now have a good working version of `get_bad_formal_immersion_data(d)`  in the _Oesterle for type 1 primes combined_ worksheet.

I also added some optimization making it now really fast for degrees up to 12 (there seems to be a weird switching point at degree 13).  So depending of what you think of these timings it might mean we could just as well skip the caching.

```1
CPU times: user 6.06 ms, sys: 3.71 ms, total: 9.76 ms
Wall time: 9.6 ms
2
CPU times: user 27.2 ms, sys: 0 ns, total: 27.2 ms
Wall time: 26.9 ms
3
CPU times: user 66.8 ms, sys: 90 µs, total: 66.9 ms
Wall time: 68.3 ms
4
CPU times: user 148 ms, sys: 0 ns, total: 148 ms
Wall time: 147 ms
5
CPU times: user 155 ms, sys: 3.82 ms, total: 159 ms
Wall time: 159 ms
6
CPU times: user 272 ms, sys: 0 ns, total: 272 ms
Wall time: 272 ms
7
CPU times: user 345 ms, sys: 3.66 ms, total: 349 ms
Wall time: 348 ms
8
CPU times: user 405 ms, sys: 0 ns, total: 405 ms
Wall time: 404 ms
9
CPU times: user 677 ms, sys: 3.22 ms, total: 680 ms
Wall time: 680 ms
10
CPU times: user 882 ms, sys: 3.6 ms, total: 885 ms
Wall time: 885 ms
11
CPU times: user 1.25 s, sys: 11.4 ms, total: 1.26 s
Wall time: 1.26 s
12
CPU times: user 1.59 s, sys: 11.4 ms, total: 1.6 s
Wall time: 1.6 s```

additionally found the way you were using get_bad_formal_immersion_data was wrong, it was returning a dictionary that mapped the primes p to the product of the q one is not able to use as auxiliary primes, while you were using it as if it mapped auxiliary primes q to the product of the primes p that one cannot use! I changed the behaviour of get_bad_formal_immersion_data to behave as you want to use it in other functions.

**Comment by BarinderBanwait** [comment]
Looks great @koffie! Assigning to you and closing out
