### ISSUE TITLE
Find best possible lower bound on aux primes in Type 1 case

### ISSUE THREAD

**Issue by BarinderBanwait** [isogeny-primes/isogeny-primes#5]
https://github.com/isogeny-primes/isogeny-primes/blob/990bf0b99178bd3c60a308dd0feff5164df4b517/isogeny_primes.py#L157

The current implementation takes auxiliary primes starting from 7, because this is what Momose writes for quadratic fields.

According to @koffie , after work of Parent, this can be removed, and we can take aux primes starting at 2.

This could massively improve the bounds we get.

Done is: Fill in the details here, work out what is true.

**Comment by koffie** [comment]
This issue is mostly solved by the discussion on #2, with the comments there we can take Q_2=3.

Unless we have a major theoretical breakthrough it is not possible to just take Q_2 = 2, since we don't now how to prove that q=2 can be used for all primes p greater then some constant p_0. However there are some explicit combinations of d,p for which know we can use q = 2 (see lemma 5.4 of [https://arxiv.org/pdf/1707.00364.pdf](https://arxiv.org/pdf/1707.00364.pdf)). This could be used to remove certain primes < 2281 from get_type_1_primes .

**Comment by BarinderBanwait** [comment]
All of this has been addressed. We are even using `formal_immersion_at_2` filtering.
