### ISSUE TITLE
Compute uniform multiplicative bounds

### ISSUE THREAD

**Issue by BarinderBanwait** [isogeny-primes/isogeny-primes#97]
The uniform bounds paper is nearing completion; we now have a handle on what the multiplicative bounds should be (Theorem 1.2), and how to compute them (various Algorithms in the manuscript). This issue is to do this implementation.

I intend to change the usability of `isogeny_primes` CLI, by allowing the user to pass in a degree `d`, and the output will be the nonzero integers for the epsilons we can deal with in Theorem 1.2.

**Comment by koffie** [comment]
This sounds good. I think a useful feature will also be to be able to pass in the two integers d and e with 0 <= e <= 12d where e is the trace of epsilon. Since I think especially the e=6 mod 12 might take significantly more time than the others. So if for example people are only interested in the "p"-unramified isogenies they can pass in e=0 and get the bound for that.

On a personal level I would for example be very interested to see if we can get the exact list for `tr eps = 0` for d=2 for example.

**Comment by BarinderBanwait** [comment]
This is addressed by #98 ; a follow-up issue to improve the CLI has been declared as #101
